
#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using Sitecore.Globalization;
using Sitecore.Data;

namespace FocusPoints.Models
{
	public static partial class VersionedImageConstants {

		public const string TemplateIdString = "c97ba923-8009-4858-bdd5-d8be5fccecf7";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Image";

		public static readonly ID FocusPointFieldId = new ID("fc10562f-64ea-4485-b655-2c758620b1dc");
		public const string FocusPointFieldName = "FocusPoint";
	}
}
namespace FocusPoints.Models
{
	public static partial class UnversionedImageConstants {

		public const string TemplateIdString = "f1828a2c-7e5d-4bbd-98ca-320474871548";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Image";

		public static readonly ID FocusPointFieldId = new ID("d015a066-31e4-4c80-afb8-47f66b2ec99e");
		public const string FocusPointFieldName = "FocusPoint";
	}
}
